name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-docker-repo:$(date +%s)
    - name: Login to Docker Hub
      run: docker login -u santhosh88896 -p sandY@sensiple@intelisense@12345
    - name: Push Docker image to Docker Hub
      run: docker push santhosh88896/my-docker-repo:$(date +%s)
